
dependencies {
    api platform("io.netty:netty-bom:$nettyVersion")
    api platform("com.fasterxml.jackson:jackson-bom:$jackson2Version")

    api "io.eventuate.common:eventuate-common-coordination-leadership:$eventuateCommonVersion"

    api "org.springframework.boot:spring-boot-starter-data-redis:$springBootVersion"
    api "org.redisson:redisson:$redissonVersion"
    api "org.apache.commons:commons-lang3:$commonsLang3Version"

    testImplementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-data-redis-test:$springBootVersion"
}
